apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sync
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  description: Project used to Sync the Argo CD Application and ApplicationSet CR
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet
  destinations:
    - namespace: argocd
      server: https://argocd.lrsslv.dev
  sourceRepos:
    - https://github.com/laasilva/argo-cd